// W8f-b F1–F3. Baseline is the actual pre-w8f-b HTML, not recolouring the new build.
// F1 as revised by the user on 2026-10-08 (option a): the distant forest at d = 300 must match the same place's real trees (d = 70, all instances loaded) within 15 levels
// (RGB distance of the forest-pixel means; places whose d = 70 frame has < 200 forest pixels skip it), and its luminance std must not fall below pre-w8f-b's.
// The old "both >= 1.5 x baseline" asked for a distant forest about 3 x darker than the real trees and contradicted E3; its ratios are still printed.
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {execFileSync} from 'node:child_process';import {pathToFileURL} from 'node:url';import {launchChromium} from './browser.mjs';import {INIT} from './road_views.mjs';
const out='docs/world/w8f-b',args=process.argv.slice(2),browser=await launchChromium(),rows=[],errors=[];fs.mkdirSync(out,{recursive:true});
const baseFile=path.join(fs.mkdtempSync(path.join(os.tmpdir(),'w8fb-')),'index.html');fs.writeFileSync(baseFile,execFileSync('git',['show','pre-w8f-b:index.html'],{maxBuffer:40e6}));
async function open(file){const p=await browser.newPage({viewport:{width:1280,height:800}});p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(INIT);await p.goto(pathToFileURL(path.resolve(file)).href,{timeout:120000});await p.waitForFunction(()=>window.__scene,null,{timeout:120000});await p.evaluate(()=>window.__step(2));return p;}
const cur=await open('index.html'),base=await open(baseFile);
const near={},places=[['forest',-15,-40],['farm',-71.8/90*180/Math.PI,Math.atan(Math.sinh(12.3/90))*180/Math.PI],['grass',90,-42]];
async function place(p,lo,la,d,mode='sphere',matrix=null){return p.evaluate(([lo,la,d,mode,matrix])=>{const S=window.__scene,q=WORLD.lonLatToTown(lo,la);S.weather.lock('clear');S.view.set({target:[q.x,1.2,q.z],dist:d,yaw:lo< -40&&la>0&&la<10?2.5:0,pitch:lo< -40&&la>0&&la<10?.55:1.2});S.transition.setMode(mode);S.transition.step(3);window.__step(1);const c=S.camera;if(matrix){c.position.fromArray(matrix.pos);c.quaternion.fromArray(matrix.quat);c.up.fromArray(matrix.up);c.updateMatrixWorld();}S.cover.tick(1.2,c);S.section.tick(1.2,c);S.roads.tick(1.2,c);S.ocean.tick(1.2,c);S.renderer.render(S.scene,c);const start=Date.now();S.renderer.render(S.scene,c);const gl=S.renderer.getContext();gl.finish();return{pos:c.position.toArray(),quat:c.quaternion.toArray(),up:c.up.toArray(),h:c.position.distanceTo(new THREE.Vector3(0,-90,0))-90,info:{...S.renderer.info.render},ms:Date.now()-start,distant:S.cover.state.distant};},[lo,la,d,mode,matrix]);}
const shot=p=>p.evaluate(()=>{const S=window.__scene;S.renderer.render(S.scene,S.camera);return S.renderer.domElement.toDataURL('image/png');});
async function stats(p,url){return p.evaluate(async url=>{const S=window.__scene,T=THREE,cam=S.camera,img=new Image();img.src=url;await img.decode();const canvas=document.createElement('canvas');canvas.width=1280;canvas.height=800;const ctx=canvas.getContext('2d');ctx.drawImage(img,0,0);const data=ctx.getImageData(0,0,1280,800).data;cam.updateMatrixWorld();const ray=new T.Raycaster(),ctr=new T.Vector3(0,-90,0),sphere=new T.Sphere(ctr,90),P=new T.Vector3(),a={};for(let y=0;y<800;y+=4)for(let x=0;x<1280;x+=4){ray.setFromCamera(new T.Vector2(2*(x+.5)/1280-1,1-2*(y+.5)/800),cam);if(!ray.ray.intersectSphere(sphere,P))continue;P.sub(ctr);const reg=WORLD.regionAt(Math.atan2(P.x,P.y)*180/Math.PI,Math.asin(-P.z/90)*180/Math.PI),k=reg.kind,i=4*(y*1280+x),rgb=[data[i],data[i+1],data[i+2]],l=.2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2],v=a[k]||(a[k]={n:0,sum:[0,0,0],l:0,l2:0});v.n++;rgb.forEach((c,j)=>v.sum[j]+=c);v.l+=l;v.l2+=l*l;}const res={};for(const[k,v]of Object.entries(a))res[k]={n:v.n,rgb:v.sum.map(c=>c/v.n),std:Math.sqrt(Math.max(0,v.l2/v.n-(v.l/v.n)**2))};return res;},url);}
function report(name,ok,data){rows.push({name,ok,data});console.log(`${ok?'PASS':'FAIL'} ${name} ${JSON.stringify(data)}`);fs.writeFileSync(out+(args.includes('--f2')?'/distant-f2-results.json':args.includes('--metrics')?'/distant-metrics-results.json':'/distant-results.json'),JSON.stringify(rows,null,2));}
if(!args.includes('--f2')){
 for(const[name,lo,la]of places)for(const[d,mode]of [...(args.includes('--metrics')?[[70,'sphere'],[300,'sphere']]:[[30,'sphere'],[70,'sphere'],[140,'sphere'],[300,'sphere'],[70,'flat']])]){const cm=await place(cur,lo,la,d,mode),bm=await place(base,lo,la,d,mode,cm),cu=await shot(cur),bu=await shot(base);for(const[label,u]of [['current',cu],['baseline',bu]])fs.writeFileSync(`${out}/${name}-${mode}-d${d}-${label}.png`,Buffer.from(u.split(',')[1],'base64'));if(mode==='sphere'&&d===70)near[name]=(await stats(cur,cu)).forest;if(mode==='sphere'&&cm.h>=150){const c=await stats(cur,cu),b=await stats(base,bu),n=near[name],trees=n&&n.n>=200&&c.forest?Math.hypot(...c.forest.rgb.map((v,i)=>v-n.rgb[i])):null,metric=s=>({color:s.forest&&s.grassland?Math.hypot(...s.forest.rgb.map((v,i)=>v-s.grassland.rgb[i])):null,std:s.forest?.std}),C=metric(c),B=metric(b);report('F1 '+name,!!c.forest&&!!b.forest&&(trees===null||trees<=15)&&C.std>=B.std,{toTrees:trees,trees:n?{n:n.n,rgb:n.rgb,std:n.std}:null,stdRatio:C.std/B.std,oldColorRatio:C.color/B.color,current:C,baseline:B,counts:{current:c,baseline:b},camera:cm});}}
 const c=await place(cur,0,0,350),b=await place(base,0,0,350,'sphere',c),defaults=[];for(const p of [cur,base])defaults.push(await p.evaluate(()=>{const S=window.__scene;S.transition.setMode('flat');S.transition.step(3);S.view.set({target:[-7,1.2,20],dist:34,yaw:2.5,pitch:.5});window.__step(2);S.renderer.render(S.scene,S.camera);return{...S.renderer.info.render};}));report('F3 全景预算',c.info.calls-b.info.calls<=10&&c.info.triangles-b.info.triangles<=200000&&c.distant.groups<=8000&&defaults[0].calls===2374&&defaults[0].triangles===239958,{current:c,baseline:b,defaults});
}
if(!args.includes('--f1'))for(const[name,lo,la]of places){await place(cur,lo,la,20);const diffs=await cur.evaluate(([lo,la])=>{const S=window.__scene,gl=S.renderer.getContext(),w=1280,h=800,buf=new Uint8Array(w*h*4);let prev=null,diffs=[];for(let i=0;i<=60;i++){S.view.set({dist:20*Math.pow(10,i/60)});window.__step(1);S.renderer.render(S.scene,S.camera);gl.readPixels(0,0,w,h,gl.RGBA,gl.UNSIGNED_BYTE,buf);if(prev){let sum=0;for(let k=0;k<buf.length;k+=4)sum+=Math.abs(buf[k]-prev[k])+Math.abs(buf[k+1]-prev[k+1])+Math.abs(buf[k+2]-prev[k+2]);diffs.push(sum/(w*h*3));}prev=buf.slice();}return diffs;},[lo,la]);const sorted=[...diffs].sort((a,b)=>a-b),median=(sorted[29]+sorted[30])/2,max=Math.max(...diffs);report('F2 '+name,max<=3*median+.5,{max,median,diffs});}
report('页面错误',errors.length===0,errors);await browser.close();fs.rmSync(path.dirname(baseFile),{recursive:true,force:true});process.exitCode=rows.every(r=>r.ok)?0:1;
